//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IdReserva { get; set; }
        public int IdSocio { get; set; }
        public int IdActividad { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Socio Socio { get; set; }
    }
}
